#+ summary: 
#+ endpoint: https://api.collectiedata.hetnieuweinstituut.nl/datasets/the-other-interface/knowledge-graph/services/knowledge-graph/sparql

PREFIX sdo: <https://schema.org/>

CONSTRUCT {
  [] sdo:about ?sub; sdo:name ?name .
} {
  ?sub a sdo:Organization ;
  	sdo:name ?name .
  FILTER(contains(?name, ?zoekopdracht))
} 