#+ summary: 
#+ endpoint: https://api.collectiedata.hetnieuweinstituut.nl/datasets/the-other-interface/knowledge-graph/services/knowledge-graph/sparql

PREFIX sdo: <https://schema.org/>
SELECT ?sub WHERE {
  ?sub a sdo:Organization ;
  	sdo:name ?name .
  FILTER(contains(?name, "Gouda"))
} 