#+ summary: Returns organization located in the city of Gouda from IISG Archives
#+ endpoint: https://druid.datalegend.net/IISG/iisg-kg/sparql/iisg-kg

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  [] sdo:about ?sub; sdo:name ?titel .
} {
  ?sub sdo:name ?titel ;
       rdf:type sdo:Organization .
  FILTER(CONTAINS(LCASE(?titel), lcase("Gouda")))
} LIMIT 200