#+ summary: 
#+ endpoint: https://service.archief.nl/sparql

PREFIX sdo: <https://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  [] sdo:about ?sub; sdo:name ?name .
} {
  ?sub a <https://archief.nl/def/ontologie/Agent> ;
  	rdfs:label ?name .
  FILTER(contains(lcase(?name), lcase(?zoekopdracht)))
} 