#+ summary: 
#+ endpoint: https://api.rkd.triply.cc/datasets/rkd/RKD-Knowledge-Graph/services/SPARQL/sparql

PREFIX sdo: <https://schema.org/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  [] sdo:about ?sub; sdo:name ?name .
} {
  ?sub a crm:E74_Group ;
  	rdfs:label ?name ;
  	rdfs:label ?name2 .
  FILTER(contains(lcase(str(?name)), "gouda"))
  FILTER(contains(lcase(str(?name2)), lcase(?zoekopdracht)))
}